title: "My Personal Website"
description: "Welcome to my website and blog."
author: "Bob the Builder"

url: "https://zainabalidev.github.io"
baseurl: "/personal-website"


remote_theme: minima

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
