---
title: "My Personal Website"
description: "Welcome to my website and blog."
author: "Bob the Builder"

url: "https://Zainabalidev.github.io/"
baseurl: "/personal-website"

theme: []
remote_theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
